import {
  mdiChevronDown,
  mdiChevronRightCircle,
  mdiCircleMultipleOutline,
  mdiCurrencyBtc,
  mdiDevTo,
  mdiDiscord,
  mdiFlash,
  mdiGithub,
  mdiKey,
  mdiMoonWaningCrescent,
  mdiOpenSourceInitiative,
  mdiPuzzle,
  mdiReddit,
  mdiServer,
  mdiSpeedometer,
  mdiStore,
  mdiTranslate,
} from "@mdi/js"

export default {
  theme: {
    variations: false,
  },
  icons: {
    iconfont: "mdiSvg",
    values: {
      mdiTranslate,
      mdiChevronDown,
      mdiGithub,
      mdiDiscord,
      mdiReddit,
      mdiCurrencyBtc,
      mdiSpeedometer,
      mdiKey,
      mdiStore,
      mdiOpenSourceInitiative,
      mdiFlash,
      mdiServer,
      mdiCircleMultipleOutline,
      mdiDevTo,
      mdiPuzzle,
      mdiMoonWaningCrescent,
      mdiChevronRightCircle,
    },
  },
}
